---
# file: roles/openstack-full/tasks/main.yml

#- seboolean: name=rsync_client state=yes persistent=yes
#  tags: before_config
#  when: ansible_distribution == 'RedHat'

# Dirty hack to upgade /usr/sbin/edeploy before actual upgrade
# and benefit of rsync with attributes feature.
# Useful when running SElinux before J.1.0.0
- name: upgrade edeploy script
  copy: src=edeploy dest=/usr/sbin/edeploy mode=0755
  tags: before_config

# Mark the nova-compute service as disabled to prevent Nova from scheduling
# any new servers on this node
- name: disable nova-compute to prevent instance scheduling
  command: nova-manage service disable {{ ansible_fqdn }} nova-compute
  tags: before_config

- name: stop keepalived
  service: name=keepalived state=stopped
  tags: before_config

- name: stop HAproxy service
  service: name=haproxy state=stopped
  tags: before_config

- name: stop openstack services
  service: name={{ item }} state=stopped
  with_items:
    - "{{ ceilometer_agent_compute }}"
    - "{{ ceilometer_agent_notification }}"
    - "{{ ceilometer_alarm_evaluator }}"
    - "{{ ceilometer_alarm_notifier }}"
    - "{{ ceilometer_api }}"
    - "{{ ceilometer_collector }}"
    - "{{ cinder_api }}"
    - "{{ cinder_scheduler }}"
    - "{{ cinder_volume }}"
    - "{{ glance_api }}"
    - "{{ glance_registry }}"
    - "{{ heat_api }}"
    - "{{ heat_api_cfn }}"
    - "{{ heat_api_cloudwatch }}"
    - "{{ heat_engine }}"
    - "{{ keystone }}"
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
    - "{{ neutron_server }}"
    - "{{ nova_api }}"
    - "{{ nova_cert }}"
    - "{{ nova_compute }}"
    - "{{ nova_conductor }}"
    - "{{ nova_consoleauth }}"
    - "{{ nova_scheduler }}"
    - "{{ nova_spicehtml5proxy }}"
    - "{{ swift_account }}"
    - "{{ swift_container }}"
    - "{{ swift_object }}"
    - "{{ swift_proxy }}"
    - "{{ webserver }}"
  tags: before_config

# MongoDB is upgraded in RHEL7
- name: stop mongodb
  service: name=mongod state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: manage erlang_cookie migration in RabbitMQ
  script: rabbitmq-upgrade.sh {{ erlang_cookie }}
  tags: before_config

# RabbitMQ is upgraded in RHEL7
# This case is when erlang_cookie has been provided and is the same already in place.
- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: stop mysql
  service: name={{ item }} state=stopped
  with_items:
    - mysqld
    - mysql-boostrap
  tags: before_config
  ignore_errors: yes

- name: stop Ceph services
  service: name=ceph state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: stop openvswitch service
  service: name=openvswitch-switch state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: reboot the servers
  command: /sbin/reboot -t now
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: change mysqlchk port from 9200 to 8200
  replace:
    dest={{ item }}
    regexp='9200'
    replace='8200'
  with_items:
    - "/etc/services"
    - "/etc/xinetd.d/mysqlchk"
    - "/etc/haproxy/haproxy.cfg"
  tags: before_config

- name: restart xinetd
  service: name=xinetd state=restarted
  tags: before_config

- name: start openvswitch service
  service: name=openvswitch-switch state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: start Ceph services
  service: name=ceph state=started
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: start rabbitmq
  service: name=rabbitmq-server state=started
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1]

- name: bootstrap mysql cluster again
  service: name=mysql-bootstrap state=restarted
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1]

- name: restart HAproxy service
  service: name=haproxy state=restarted
  tags: before_config

# we start keepalived on the last openstack-full node, to ensure all nodes
# have xinetd updated, otherwise the VIP can come back on the first node
# while xinetd config is not updated, so HAproxy won't be able to load-balance
# MySQL.
- name: start keepalived
  service: name=keepalived state=started
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1]

- name: update keystone database
  command: keystone-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][0]

- name: start keystone service
  service: name={{ keystone }} state=started
  tags: before_config

- name: start swift services
  service: name={{ item }} state=started
  with_items:
    - "{{ swift_account }}"
    - "{{ swift_container }}"
    - "{{ swift_object }}"
    - "{{ swift_proxy }}"
  tags: before_config

- ini_file: dest=/etc/glance/glance-api.conf
            section=DEFAULT
            option=known_stores
            value=rbd
  tags: before_config

- name: update glance database
  command: glance-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][0]

- name: start glance services
  service: name={{ item }} state=started
  with_items:
    - "{{ glance_api }}"
    - "{{ glance_registry }}"
  tags: before_config

- name: update cinder database
  command: cinder-manage db sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][0]

- name: start cinder services
  service: name={{ item }} state=started
  with_items:
    - "{{ cinder_api }}"
    - "{{ cinder_scheduler }}"
    - "{{ cinder_volume }}"
  tags: before_config

- name: update neutron database
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][0]

- name: start neutron services
  service: name={{ item }} state=started
  with_items:
    - "{{ neutron_server }}"
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
  ignore_errors: yes
  tags: before_config

- name: update heat database
  command: heat-manage --config-file /etc/heat/heat.conf db_sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][0]

- name: kill heat-api process
  command: pkill -9 heat-api
  ignore_errors: yes
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: start heat services
  service: name={{ item }} state=started
  with_items:
    - "{{ heat_api_cfn }}"
    - "{{ heat_api_cloudwatch }}"
    - "{{ heat_engine }}"
  tags: before_config

- name: start ceilometer services
  service: name={{ item }} state=started
  with_items:
    - "{{ ceilometer_agent_compute }}"
    - "{{ ceilometer_agent_notification }}"
    - "{{ ceilometer_alarm_evaluator }}"
    - "{{ ceilometer_alarm_notifier }}"
    - "{{ ceilometer_api }}"
    - "{{ ceilometer_collector }}"
  tags: before_config

- name: restart ceilometer-agent-central managed by pacemaker
  command: crm resource cleanup ceilometer-agent-central
  tags: before_config
  when: ansible_distribution == 'Debian' and inventory_hostname == groups['openstack-full'][-1]

- name: restart ceilometer-agent-central managed by pacemaker
  command: pcs resource cleanup openstack-ceilometer-central
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['openstack-full'][-1]

- name: start apache2 service
  service: name={{ webserver }} state=started
  tags: before_config

- name: update nova database
  command: nova-manage db sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][0]

# Cap the compute RPC API at a version that will still be understood by your Icehouse compute nodes
- ini_file: dest=/etc/nova.conf
            section=upgrade_levels
            option=compute
            value=icehouse
  tags: before_config

# we don't restart nova-spicehtml5 because it's dropped in J.1.0.0
- name: start nova services
  service: name={{ item }} state=started
  with_items:
    - "{{ nova_api }}"
    - "{{ nova_cert }}"
    - "{{ nova_compute }}"
    - "{{ nova_conductor }}"
    - "{{ nova_consoleauth }}"
    - "{{ nova_scheduler }}"
  tags: before_config

- name: allow instance scheduling on the compute node
  command: nova-manage service enable {{ ansible_fqdn }} nova-compute
  tags: before_config

- name: Ensure old puppet ssl files are removed
  file: path=/var/lib/puppet/ssl state=absent
  tags: before_config

# Clean-up nova config by deleting the option, not useful anymore
- ini_file: dest=/etc/nova.conf
            section=upgrade_levels
            option=compute
  tags: after_config

- name: restart libvirtd service
  service: name=libvirtd state=restarted
  tags: after_config
  when: ansible_distribution == 'RedHat'

- name: restart nova services
  service: name={{ item }} state=restarted
  with_items:
    - "{{ nova_api }}"
    - "{{ nova_cert }}"
    - "{{ nova_compute }}"
    - "{{ nova_conductor }}"
    - "{{ nova_consoleauth }}"
    - "{{ nova_scheduler }}"
  tags: after_config

- name: kill neutron-server process
  command: pkill -9 neutron-server
  ignore_errors: yes
  tags: after_config
  when: ansible_distribution == 'Debian'

- name: kill keystone process
  command: pkill -9 keystone
  ignore_errors: yes
  tags: after_config
  when: ansible_distribution == 'Debian'

- name: kill glance-registry process
  command: pkill -9 glance-registry
  ignore_errors: yes
  tags: after_config
  when: ansible_distribution == 'Debian'

- name: restart some openstack services
  service: name={{ item }} state=restarted
  with_items:
    - "{{ neutron_server }}"
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
    - "{{ ceilometer_collector }}"
    - "{{ keystone }}"
    - "{{ glance_registry }}"
  tags: after_config
  ignore_errors: yes
